// <auto-generated />
using System;
using FastBusMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastBusMVC.Migrations
{
    [DbContext(typeof(final_DesignContext))]
    partial class final_DesignContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_CI_AS")
                .HasAnnotation("ProductVersion", "6.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FastBusMVC.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"), 1L, 1);

                    b.Property<string>("AdminType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("admin_type");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("pass_word");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("username");

                    b.HasKey("AdminId");

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("FastBusMVC.Models.Booking", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("book_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"), 1L, 1);

                    b.Property<DateTime>("BookingDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("booking_date_time");

                    b.Property<string>("Ticket")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("ticket");

                    b.Property<int?>("TripId")
                        .HasColumnType("int")
                        .HasColumnName("trip_id");

                    b.Property<int?>("UId")
                        .HasColumnType("int")
                        .HasColumnName("u_id");

                    b.HasKey("BookId")
                        .HasName("c23");

                    b.HasIndex("TripId");

                    b.HasIndex("UId");

                    b.ToTable("Booking", (string)null);
                });

            modelBuilder.Entity("FastBusMVC.Models.Bu", b =>
                {
                    b.Property<int>("BusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("bus_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusId"), 1L, 1);

                    b.Property<string>("BusTybe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("bus_tybe");

                    b.HasKey("BusId")
                        .HasName("c18");

                    b.ToTable("bus", (string)null);
                });

            modelBuilder.Entity("FastBusMVC.Models.SpBooking", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("book_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"), 1L, 1);

                    b.Property<DateTime>("BookingDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("booking_date_time");

                    b.Property<string>("Perpose")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("perpose");

                    b.Property<string>("RequiredSeats")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("required_seats");

                    b.Property<int?>("UId")
                        .HasColumnType("int")
                        .HasColumnName("u_id");

                    b.HasKey("BookId")
                        .HasName("c103");

                    b.HasIndex("UId");

                    b.ToTable("sp_Booking", (string)null);
                });

            modelBuilder.Entity("FastBusMVC.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("trip_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripId"), 1L, 1);

                    b.Property<string>("ArrivalCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("arrival_city");

                    b.Property<DateTime>("ArrivalDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("arrival_date_time");

                    b.Property<int?>("BusId")
                        .HasColumnType("int")
                        .HasColumnName("bus_id");

                    b.Property<string>("DeparureCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Deparure_city");

                    b.Property<DateTime>("DeparureDataTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Deparure_data_time");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("price");

                    b.Property<string>("TripImage")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("trip_image");

                    b.HasKey("TripId");

                    b.HasIndex("BusId");

                    b.ToTable("trip", (string)null);
                });

            modelBuilder.Entity("FastBusMVC.Models.TripBu", b =>
                {
                    b.Property<int?>("BusId")
                        .HasColumnType("int")
                        .HasColumnName("bus_id");

                    b.Property<int?>("TripId")
                        .HasColumnType("int")
                        .HasColumnName("trip_id");

                    b.Property<int>("Code")
                        .HasColumnType("int")
                        .HasColumnName("code");

                    b.Property<int?>("SeatNumber")
                        .HasColumnType("int")
                        .HasColumnName("seat_number");

                    b.HasKey("BusId", "TripId")
                        .HasName("c102");

                    b.HasIndex("TripId");

                    b.HasIndex(new[] { "Code" }, "c101")
                        .IsUnique();

                    b.ToTable("bus_trip", (string)null);
                });

            modelBuilder.Entity("FastBusMVC.Models.TTicket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ticket_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"), 1L, 1);

                    b.Property<int?>("AvilableTicket")
                        .HasColumnType("int")
                        .HasColumnName("avilable_ticket");

                    b.Property<int?>("BookedTicket")
                        .HasColumnType("int")
                        .HasColumnName("booked_ticket");

                    b.Property<int>("NumberTicket")
                        .HasColumnType("int")
                        .HasColumnName("number_ticket");

                    b.Property<int?>("TribId")
                        .HasColumnType("int")
                        .HasColumnName("trib_id");

                    b.HasKey("TicketId")
                        .HasName("c21");

                    b.HasIndex("TribId");

                    b.ToTable("t_ticket", (string)null);
                });

            modelBuilder.Entity("FastBusMVC.Models.User", b =>
                {
                    b.Property<int>("UId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("u_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UId"), 1L, 1);

                    b.Property<string>("BathDate")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("bath_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gendr")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("gendr");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("last_name");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasMaxLength(155)
                        .IsUnicode(false)
                        .HasColumnType("varchar(155)")
                        .HasColumnName("pass_word");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone");

                    b.Property<string>("UImage")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("u_image");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("username");

                    b.HasKey("UId")
                        .HasName("c12");

                    b.HasIndex(new[] { "Email" }, "c14")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "c15")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "c16")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("FastBusMVC.Models.Booking", b =>
                {
                    b.HasOne("FastBusMVC.Models.Trip", "Trip")
                        .WithMany("Bookings")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("c24");

                    b.HasOne("FastBusMVC.Models.User", "UIdNavigation")
                        .WithMany("Bookings")
                        .HasForeignKey("UId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("c39");

                    b.Navigation("Trip");

                    b.Navigation("UIdNavigation");
                });

            modelBuilder.Entity("FastBusMVC.Models.SpBooking", b =>
                {
                    b.HasOne("FastBusMVC.Models.User", "UIdNavigation")
                        .WithMany("SpBookings")
                        .HasForeignKey("UId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("c105");

                    b.Navigation("UIdNavigation");
                });

            modelBuilder.Entity("FastBusMVC.Models.Trip", b =>
                {
                    b.HasOne("FastBusMVC.Models.Admin", "Bus")
                        .WithMany("Trips")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("c38");

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("FastBusMVC.Models.TripBu", b =>
                {
                    b.HasOne("FastBusMVC.Models.Bu", "Bus")
                        .WithMany("BusTrips")
                        .HasForeignKey("BusId")
                        .IsRequired()
                        .HasConstraintName("FK_bus_trip_bus");

                    b.HasOne("FastBusMVC.Models.Trip", "Trip")
                        .WithMany("BusTrips")
                        .HasForeignKey("TripId")
                        .IsRequired()
                        .HasConstraintName("FK_bus_trip_trip");

                    b.Navigation("Bus");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("FastBusMVC.Models.TTicket", b =>
                {
                    b.HasOne("FastBusMVC.Models.Trip", "Trib")
                        .WithMany("TTickets")
                        .HasForeignKey("TribId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("c22");

                    b.Navigation("Trib");
                });

            modelBuilder.Entity("FastBusMVC.Models.Admin", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("FastBusMVC.Models.Bu", b =>
                {
                    b.Navigation("BusTrips");
                });

            modelBuilder.Entity("FastBusMVC.Models.Trip", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("BusTrips");

                    b.Navigation("TTickets");
                });

            modelBuilder.Entity("FastBusMVC.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("SpBookings");
                });
#pragma warning restore 612, 618
        }
    }
}
